server.port: 8081

spring:
  application:
    name: ITEM-SERVICE

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    lease-renewal-interval-in-seconds: 1
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 3
